import {
  pgTable,
  varchar,
  text,
  timestamp,
  numeric,
  bigint,
  boolean,
} from "drizzle-orm/pg-core";

export const logs = pgTable("logs", {
  id: varchar("id").primaryKey(),
  parentRequestId: varchar("parent_request_id"),
  timestamp: timestamp("timestamp", { withTimezone: true }).notNull(),
  objectType: varchar("object_type").notNull(),
  provider: varchar("provider").notNull(),
  model: varchar("model").notNull(),
  numberOfRetries: bigint("number_of_retries", { mode: "number" }).default(0),
  fallbackIndex: bigint("fallback_index", { mode: "number" }).default(0),
  selectedKeyId: varchar("selected_key_id"),
  selectedKeyName: varchar("selected_key_name"),
  virtualKeyId: varchar("virtual_key_id"),
  virtualKeyName: varchar("virtual_key_name"),
  inputHistory: text("input_history"),
  responsesInputHistory: text("responses_input_history"),
  outputMessage: text("output_message"),
  responsesOutput: text("responses_output"),
  embeddingOutput: text("embedding_output"),
  params: text("params"),
  tools: text("tools"),
  toolCalls: text("tool_calls"),
  speechInput: text("speech_input"),
  transcriptionInput: text("transcription_input"),
  speechOutput: text("speech_output"),
  transcriptionOutput: text("transcription_output"),
  cacheDebug: text("cache_debug"),
  latency: numeric("latency"),
  tokenUsage: text("token_usage"),
  cost: numeric("cost"),
  status: varchar("status").notNull(),
  errorDetails: text("error_details"),
  stream: boolean("stream").default(false),
  contentSummary: text("content_summary"),
  rawResponse: text("raw_response"),
  promptTokens: bigint("prompt_tokens", { mode: "number" }).default(0),
  completionTokens: bigint("completion_tokens", { mode: "number" }).default(0),
  totalTokens: bigint("total_tokens", { mode: "number" }).default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  rawRequest: text("raw_request"),
});

export type Log = typeof logs.$inferSelect;
